
image: clojure:lein-alpine

variables:
  REVIEW_APP_NAME: "$CI_COMMIT_REF_SLUG-$CI_PROJECT_NAME"

cache:
  paths:
    - .m2/

stages:
  - test
  - review
  - deploy

before_script:
  - lein with-profile +ci deps

test:
  script:
  - lein with-profile +ci test

coverage:
  allow_failure: true
  coverage: '/ALL FILES\W+\d+\.\d+\W+(\d+\.\d+)/'
  script:
  - lein with-profile +ci cloverage | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"

code_lint:
  script: lein with-profile +ci eastwood "{:config-files [\"eastwood.clj\"]}"

code_quality:
  script: lein with-profile +ci kibit

staging:
  image: ruby
  type: deploy
  before_script: []
  cache: {}
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev rubygems
  - gem install dpl
  - dpl --provider=heroku --app=flexblock-staging --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://flexblock-staging.herokuapp.com
  only:
  - master

review:
  stage: review
  image: ruby:2.3
  before_script: []
  cache: {}
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev curl
    - gem install dpl
    - echo "$REVIEW_APP_NAME " $REVIEW_APP_NAME
    - >-
         curl
         -n
         -X POST https://api.heroku.com/apps
         -d '
         {
         "name":  "'"$REVIEW_APP_NAME"'",
         "region": "us",
         "stack": "heroku-16"
         }
         '
         -H "Content-Type: application/json"
         -H "Accept: application/vnd.heroku+json; version=3"
         -H "Authorization: Bearer $HEROKU_API_KEY"
    - >-
         curl
         -n
         -X POST https://api.heroku.com/apps/$REVIEW_APP_NAME/addons
         -d '
         {
         "attachment": {"name": "DATABASE"},
         "plan": "heroku-postgresql:hobby-dev"
         }
         '
         -H "Content-Type: application/json"
         -H "Accept: application/vnd.heroku+json; version=3"
         -H "Authorization: Bearer $HEROKU_API_KEY"
    - dpl --provider=heroku --app=$REVIEW_APP_NAME --api-key=$HEROKU_API_KEY

  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_SLUG-$CI_PROJECT_NAME.herokuapp.com
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: review
  image: ruby:2.3
  before_script: []
  cache: {}
  script:
    - echo "environment is getting deployed !"
    - >-
         curl
         -n
         -X DELETE https://api.heroku.com/apps/$REVIEW_APP_NAME
         -H "Content-Type: application/json"
         -H "Accept: application/vnd.heroku+json; version=3"
         -H "Authorization: Bearer $HEROKU_API_KEY"

  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

pages:
  stage: deploy
  image: alpine
  before_script: []
  cache: {}
  script:
    - apk add npm git
    - npm install gitbook-cli -g
    - gitbook fetch 3.2.3
    - gitbook build doc public
  artifacts:
    paths:
      - public
  only:
    - master
