image: clojure:lein-alpine

cache:
  paths:
    - .m2/

before_script:
  - lein with-profile +ci deps

test:
  script:
  - lein with-profile +ci test

coverage:
  allow_failure: true
  coverage: '/ALL FILES\W+\d+\.\d+\W+(\d+\.\d+)/'
  script:
  - lein with-profile +ci cloverage | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"

code_quality:
  script: lein with-profile +ci kibit

staging:
  image: alpine/git
  type: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_STAGING_API_KEY@git.heroku.com/flexblock-staging.git
  - git push -f heroku master
  only:
  - master
