image: clojure:lein-2.7.0

before_script:
  - lein deps

test:
  script:
  - lein test

coverage:
  allow_failure: true
  coverage: '/ALL FILES\W+\d+\.\d+\W+(\d+\.\d+)/'
  script:
  - lein cloverage

staging:
  type: deploy
  script:
  - git remote add heroku https://heroku:$HEROKU_STAGING_API_KEY@git.heroku.com/flexblock-staging.git
  - git push -f heroku master
  only:
  - master