(ns flexblock.views.loading
  "Funny loading messages.")

(def messages
  "Fun messages to display while the page is loading.
  This list should be in alphabetical order. Selection is random.
  Some inspiration taken from:
  https://github.com/1egoman/funnies/blob/master/src/funnies.js"
  ["...at least you're not on hold..."
   "@todo Insert witty loading message"
   "99 bottles of beer on the wall..."
   "A different loading message? Finally, some progress!"
   "All your web browser are belong to us!"
   "Are we there yet?"
   "Cleaning off the cobwebs..."
   "Configuring quantum superposition..."
   "Constructing additional pylons..."
   "Convincing AI not to turn evil..."
   "Cracking military-grade encryption..."
   "Definitely not a virus..."
   "Didn't know paint dried so quickly."
   "Distracted by cat gifs, please hold."
   "Dividing by zero..."
   "Downloading more RAM.."
   "DROP TABLE \"users\";<br />What have I done‽"
   "Feel free to spin in your chair."
   "Follow the white rabbit."
   "Fork me on GitLab!"
   "Generating witty dialogue..."
   "Get some coffee and come back in ten minutes."
   "git happens"
   "Hang on a sec, I know your data is here somewhere!"
   "Help! I'm trapped in a loading message factory!"
   "How about this weather, eh?"
   "How did you get here?"
   "I swear it's almost done."
   "I think I am, therefore, I am. I think."
   "If a website loaded slowly in the middle of the forest, would
users still complain?"
   "If I’m not back in five minutes, just wait longer."
   "Initializing the initializer..."
   "I'm going to walk the dog. Be right back."
   "Is this Windows?"
   "It looks like you're waiting for a website to load..."
   "It's still faster than you could draw it."
   "Jumping to hyperspace..."
   "Kindly hold on as we convert this bug to a feature..."
   "Last call for the data bus! All aboard!"
   "Linking to deep-space probes..."
   "Loading funny message..."
   "Loading infinite monkeys..."
   "Looking for sense of humor, please hold on."
   "Making sure all the i's have dots..."
   "Mining some bitcoins..."
   "My other load screen is much faster. You should try that one
instead."
   "Obfuscating quantum entanglement."
   "Observe harder!"
   "Optimism is a lack of information."
   "Please wait... Consulting the manual..."
   "Please hold on as we reheat our coffee."
   "Please wait while a larger software vendor in Seattle takes over
the world."
   "Please wait, while we purge the Decepticons for you. Yes, You can
thanks us later!"
   "Please wait while we test your patience..."
   "Please wait until the sloth starts moving."
   "Proving P=NP..."
   "Putting the icing on the cake. The cake is not a lie..."
   "Reading Terms and Conditions..."
   "Reporting statistics to Facebook..."
   "Simulating traveling salesman..."
   "Shovelling coal into the server..."
   "Still faster than Windows update."
   "There is no spoon. Because we are not done loading it."
   "This is not a joke, it's a commit."
   "TODO: Insert elevator music."
   "Twiddling thumbs..."
   "Unicorns are at the end of this road, I promise."
   "User: the word computer professionals use when they mean !!idiot!!"
   "Wait, do you smell something burning?"
   "Web developers do it with &lt;style&gt;"
   "Well, what are you waiting for?"
   "We're gonna need a faster connection!"
   "Winter is coming..."
   "Yes, there really are magic elves with an abacus working
frantically in here."
   "You shall not pass! yet..."
   "Your time is very important to us. Please wait while we ignore
you..."])
